[build]
  command = "npm run build"
  publish = "dist"

# Proxy API calls directly to Apps Script (works for GET and POST)
[[redirects]]
  from = "/api/*"
  to = "https://script.google.com/macros/s/AKfycbx3Ve1GOp90lyHgugxSZ7uSVMJaq6a4bXqCd-Imn0O5MikCV1010kjBLlIBQAHTfGFf/exec"
  status = 200

# SPA fallback (Vue Router history mode)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

