[build]
  command = "npm run build"
  publish = "dist"

# Only keep the SPA fallback - remove API redirects since we're using functions
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

